name: Continuous integration
#on: [pull_request, push]
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      triggerIos:
        description: 'Run iOS tests'
        required: true
        default: 'yes'
      triggerMacos:
        description: 'Run macOS tests'
        required: true
        default: 'yes'
      trigger3DS:
        description: 'Run 3DS tests'
        required: true
        default: 'yes'
jobs:
  windows:
    runs-on: windows-latest
    defaults:
       run:
         shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'
      - run: pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config make mingw-w64-x86_64-python3 mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng git
      - run: make -j2 PLATFORM=simulator
      - run: make -j2 PLATFORM=simulator test.exe
      - run: cmd /c output\release\simulator\windows\test.exe --headless
      - # if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: actions/checkout@main
        with:
          repository: mickbot-92/Upsilon-binfiles
          ref: 'main'
          token:  ${{ secrets.PAT_UPSILON_BINFILES }}
          path: 'binfiles'
      # TODO: Handle git conflicts using rebase
      - name: Upload binary files to website
        # if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon'}}
        run: |
          cp -r output/release/simulator/windows/epsilon.exe binfiles/binaries/dev/simulator
          cd binfiles
          git add -A
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Upsilon CI"
          git pull
          git commit -m "Update from CI"
          git push
      - uses: actions/upload-artifact@main
        with:
          name: epsilon-windows.exe
          path: output/release/simulator/windows/epsilon.exe

env:
  ACCEPT_OFFICIAL_TOS: 1
