name: Continuous integration
#on: [pull_request, push]
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      triggerIos:
        description: 'Run iOS tests'
        required: true
        default: 'yes'
      triggerMacos:
        description: 'Run macOS tests'
        required: true
        default: 'yes'
      trigger3DS:
        description: 'Run 3DS tests'
        required: true
        default: 'yes'
jobs:
  macos:
    if: github.event.inputs.triggerMacos == 'yes' || github.event.inputs.triggerMacos == ''
    runs-on: macOS-latest
    steps:
      - run: |
          brew install imagemagick
          python3 -m venv .venv
          .venv/bin/pip3 install setuptools lz4 pypng stringcase
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - run: make -j2 PLATFORM=simulator
      - run: make -j2 PLATFORM=simulator ARCH=x86_64 test.bin
      - run: output/release/simulator/macos/x86_64/test.bin --headless
      - uses: actions/upload-artifact@v7
        with:
          name: epsilon-macos.zip
          path: output/release/simulator/macos/epsilon.app
      - if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: actions/checkout@v6
        with:
          repository: Yaya-Cout/Upsilon-binfiles
          ref: 'main'
          token:  ${{ secrets.PAT_UPSILON_BINFILES }}
          path: 'binfiles'
      # TODO: Handle git conflicts using rebase
      - name: Upload binary files to website
        if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon'}}
        run: |
          cp -r output/release/simulator/macos/epsilon.app binfiles/binaries/dev/simulator
          cd binfiles
          git add -A
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Upsilon CI"
          git pull
          git commit -m "Update from CI"
          git push
  ios:
    if: github.event.inputs.triggerIos == 'yes' || github.event.inputs.triggerIos == ''
    runs-on: macos-14
    steps:
      - run: |
          brew install imagemagick
          python3 -m venv .venv
          .venv/bin/pip3 install setuptools lz4 pypng stringcase
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - run: make -j2 PLATFORM=simulator TARGET=ios EPSILON_TELEMETRY=0
      - run: make -j2 PLATFORM=simulator TARGET=ios EPSILON_TELEMETRY=0 APPLE_PLATFORM=ios-simulator
      - uses: actions/upload-artifact@v7
        with:
          name: epsilon-ios.ipa
          path: output/release/simulator/ios/epsilon.ipa
      - if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon' }}
        uses: actions/checkout@v6
        with:
          repository: Yaya-Cout/Upsilon-binfiles
          ref: 'main'
          token:  ${{ secrets.PAT_UPSILON_BINFILES }}
          path: 'binfiles'
      # TODO: Handle git conflicts using rebase
      - name: Upload binary files to website
        if: ${{ github.event_name == 'push' && github.ref_name == 'upsilon-dev' && github.repository == 'UpsilonNumworks/Upsilon'}}
        run: |
          cp -r output/release/simulator/ios/epsilon.ipa binfiles/binaries/dev/simulator
          cd binfiles
          git add -A
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Upsilon CI"
          git pull
          git commit -m "Update from CI"
          git push

env:
  ACCEPT_OFFICIAL_TOS: 1
